// Generated by CoffeeScript 2.4.1
var assign_events, load_complete;

import {
  Map
} from '../js/unco-mapa.js';

assign_events = function() {
  var btn;
  btn = document.querySelector('.btn-highlight');
  return btn.addEventListener('click', function() {
    var name, sel;
    sel = document.querySelector('select.classroom');
    name = sel.value;
    return cr_map.highlight(name);
  });
};

export var fill_select = function() {
  var lst_ids, select;
  lst_ids = cr_map.get_classrooms();
  lst_ids.sort(function(first, second) {
    return second.name < first.name;
  });
  select = document.querySelector('select.classroom');
  return lst_ids.forEach((idobj) => {
    var op;
    op = "<option value=\"" + idobj.id + "\">";
    op = op + idobj.name + "</option>";
    return select.innerHTML = select.innerHTML.concat(op);
  });
};

load_complete = function() {
  var height, svg, width;
  fill_select();
  svg = document.querySelector('svg');
  width = svg.getAttribute('width');
  height = svg.getAttribute('height');
  svg.setAttribute('width', width / 2);
  return svg.setAttribute('height', height / 2);
};

console.log('loading map...');

export var cr_map = new Map(document.querySelector('.map'), load_complete);

assign_events();
