// Generated by CoffeeScript 2.4.1
var assign_events;

import {
  Map
} from '../js/unco-mapa.js';

assign_events = function() {
  var btn;
  btn = document.querySelector('.btn-highlight');
  return btn.addEventListener('click', function() {
    var name, txt;
    txt = document.querySelector('.txt-classroom');
    name = txt.value;
    return cr_map.highlight(name);
  });
};

console.log('loading map...');

export var cr_map = new Map(document.querySelector('.map'));

assign_events();
